### ISSUE TITLE
The latest kernel is not here

### ISSUE THREAD

**Issue by AnonymousRetard** [droboports/kernel-drobo5n#1]
My drobo 5N is running kernel 3.2.58-2. This version does not seem to be in this repository.

**Comment by ricardopadilha** [comment]
The "-2" means Drobo changed the kernel configuration in a way that will make current modules not to load. Last time they did something like that was when SELinux support was enabled in the kernel.

In other words, the kernel code remains the same, and you just need to grab the configuration from /proc/config.gz on you Drobo.

**Comment by vikulin** [comment]
@ricardopadilha does it work for Drobo5N 3.2.96-3 kernel?
